export function CertGrid() {
  return (
    <div className="cert-grid-section" id="certs" style={{background: 'var(--surface)', borderTop: '1px solid var(--border)', borderBottom: '1px solid var(--border)'}}>
      <div className="cert-grid-inner" style={{maxWidth: 1160, margin: '0 auto', padding: '64px 48px'}}>
        <div className="section-header" style={{marginBottom: 28}}>
          <div className="section-kicker" style={{display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 11, fontWeight: 700, color: 'var(--red)', letterSpacing: '1.4px', textTransform: 'uppercase', marginBottom: 16}}>
            <span style={{display: 'inline-block', width: 16, height: 1, background: 'var(--red)'}}></span>
            Supported Certifications
          </div>
          <h2 className="section-title" style={{fontSize: 32, fontWeight: 500, color: 'var(--text)', lineHeight: 1.18, letterSpacing: '-0.015em'}}>58 major certification tracks supported</h2>
        </div>
        <div className="cert-categories" style={{display: 'flex', gap: 8, marginBottom: 32, flexWrap: 'wrap'}}>
          <button className="cert-cat-btn active" style={{background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 14px', fontSize: 13, fontWeight: 500, color: 'var(--text-4)', cursor: 'pointer', fontFamily: 'var(--font)', transition: 'all 0.15s'}}>All</button>
          <button className="cert-cat-btn" style={{background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 14px', fontSize: 13, fontWeight: 500, color: 'var(--text-4)', cursor: 'pointer', fontFamily: 'var(--font)', transition: 'all 0.15s'}}>National IT</button>
          <button className="cert-cat-btn" style={{background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 14px', fontSize: 13, fontWeight: 500, color: 'var(--text-4)', cursor: 'pointer', fontFamily: 'var(--font)', transition: 'all 0.15s'}}>Cloud</button>
          <button className="cert-cat-btn" style={{background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 14px', fontSize: 13, fontWeight: 500, color: 'var(--text-4)', cursor: 'pointer', fontFamily: 'var(--font)', transition: 'all 0.15s'}}>Database</button>
          <button className="cert-cat-btn" style={{background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 14px', fontSize: 13, fontWeight: 500, color: 'var(--text-4)', cursor: 'pointer', fontFamily: 'var(--font)', transition: 'all 0.15s'}}>Security</button>
          <button className="cert-cat-btn" style={{background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 14px', fontSize: 13, fontWeight: 500, color: 'var(--text-4)', cursor: 'pointer', fontFamily: 'var(--font)', transition: 'all 0.15s'}}>Network</button>
          <button className="cert-cat-btn" style={{background: 'transparent', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 14px', fontSize: 13, fontWeight: 500, color: 'var(--text-4)', cursor: 'pointer', fontFamily: 'var(--font)', transition: 'all 0.15s'}}>Data/AI</button>
        </div>
        <div className="cert-tags-wrap" style={{display: 'flex', flexWrap: 'wrap', gap: 8}}>
          <span className="cert-tag popular" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--green)'}}></span>Engineer Information Processing<span className="cert-popular-label" style={{fontSize: 10, fontWeight: 700, color: 'var(--green)', background: 'var(--green-dim)', borderRadius: 4, padding: '1px 6px', letterSpacing: 0.4}}>Popular</span></span>
          <span className="cert-tag popular" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--green)'}}></span>SQLD<span className="cert-popular-label" style={{fontSize: 10, fontWeight: 700, color: 'var(--green)', background: 'var(--green-dim)', borderRadius: 4, padding: '1px 6px', letterSpacing: 0.4}}>Popular</span></span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Engineer Information Security</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Network Manager Level 1</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Computer Literacy Level 1</span>
          <span className="cert-tag popular" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--green)'}}></span>AWS SAA<span className="cert-popular-label" style={{fontSize: 10, fontWeight: 700, color: 'var(--green)', background: 'var(--green-dim)', borderRadius: 4, padding: '1px 6px', letterSpacing: 0.4}}>Popular</span></span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>AWS SAP</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>AWS DVA</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Linux Master Level 1</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Linux Master Level 2</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>SQLP</span>
          <span className="cert-tag popular" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--green)'}}></span>Engineer Big Data Analysis<span className="cert-popular-label" style={{fontSize: 10, fontWeight: 700, color: 'var(--green)', background: 'var(--green-dim)', borderRadius: 4, padding: '1px 6px', letterSpacing: 0.4}}>Popular</span></span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>ADsP</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Industrial Engineer Information Processing</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>CCNA</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>CCNP</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Google Cloud ACE</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Azure AZ-900</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Information Systems Auditor</span>
          <span className="cert-tag" style={{background: 'var(--surface-3)', border: '1px solid var(--border)', borderRadius: 8, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: 'var(--text-3)', cursor: 'pointer', transition: 'all 0.15s', letterSpacing: 0.1, display: 'flex', alignItems: 'center', gap: 6}}><span className="ct-dot" style={{width: 5, height: 5, borderRadius: '50%', background: 'var(--border-mid)'}}></span>Engineer Computer Systems Applications</span>
        </div>
      </div>
    </div>
  );
}
